### ISSUE TITLE
how to get geschaeftskunden credentials 

### ISSUE THREAD

**Issue by rudracomputech** [netresearch/dhl-sdk-api-bcs#3]
Hi 
I am trying to implement your API on my Laravel project but not able to get below details. How can I get below details 
'appId', 'appToken', 'user', 'signature'

**Comment by powli** [comment]
Hello @rudracomputech,

`appId` and `appToken` identify the application itself - see https://entwickler.dhl.de/en/group/ep/authentifizierung for more information.

`user` and `signature` refer to the specific business customer, please see https://entwickler.dhl.de/en/group/ep/wsapis/geschaeftskundenversand/current/authentifizierung for more information.

**Comment by powli** [comment]
> Extra info: because this SDK is usually (but not exclusively) used in Magento, [this FAQ article](https://dhl.support.netresearch.de/support/solutions/articles/12000023252) might also help what those things are and where they get used.

Thank you, @ngolatka. This information applies to the `user` and `signature` pair.

**Comment by rudracomputech** [comment]
Hello @powli ,
Thankyou for your reply,
It was not clear in document, if anyone else having same situation please take below explanations

For sandbox -
**appId**       -  'Your developer app id'
**appToken** -  'Your login password'
**user**          -  '2222222222_01'
**signature**  -  'pass'

For live
**appId**       -  'appid given by support'
**appToken** -  'token given by support'
**user**          -  'portal username'
**signature**  -  'portal password'
