### ISSUE TITLE
International Shipping Sender Endorsement

### ISSUE THREAD

**Issue by talha-core** [netresearch/dhl-sdk-api-bcs#6]
Error:
```
Error 400: 0 of 1 shipment validated OK. Details included.
[1] A hard validation error occured in the shipment.
Warning (services.endorsement): Please note that for Shipments using the product &quot;DHL Paket International&quot; the service &quot;Endorsement (Sender's Instructions)&quot; is mandatory.
```

In `ShipmentOrderRequestBuilderInterface.php`
I can see:
```php
public const ENDORSEMENT_TYPE_IMMEDIATE = 'IMMEDIATE';
public const ENDORSEMENT_TYPE_ABANDONMENT = 'ABANDONMENT';
```

But in the API documentations it seems that type is `RETURN` :

![image](https://github.com/netresearch/dhl-sdk-api-bcs/assets/124266517/b8f0bfe7-ec16-43eb-a91f-a98b98536d6e)

```php
$this->requestBuilder = new ShipmentOrderRequestBuilder(ShipmentOrderRequestBuilder::REQUEST_TYPE_REST);
$this->requestBuilder->setShipmentEndorsementType(ShipmentOrderRequestBuilderInterface::ENDORSEMENT_TYPE_IMMEDIATE);
```

Does `IMMEDIATE` means `RETURN` ? Thanks.

**Comment by mam08ixo** [comment]
Hi @talha-core, the SDK service value gets transformed to the API value in the request builder:

https://github.com/netresearch/dhl-sdk-api-bcs/blob/2ae9459388b136db92f9eb4a1883960b18e0b3b6/src/RequestBuilder/RestRequestBuilder.php#L188-L197

So yes, in this case `IMMEDIATE` is equivalent to `RETURN`.

Did you monitor the outgoing message, is there something unexpected?

**Comment by talha-core** [comment]
Ok got it. THanks.
